export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_WISH_ITEM_COUNT = 'UPDATE_WISH_ITEM_COUNT';
